version: "3"
services:
    frontend:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: kunwalle/client
        restart: always
        volumes:
            - ./client:/usr/src/app
        ports: 
            - "3000:3000"
        expose: 
            - "3000"
            
    backend:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: kunwalle/server
        volumes:
            - ./server:/usr/src/app
            - ./cert/:/etc/backend/certs
        ports: 
            - "5000:5000"
        expose: 
            - "5000"

    wp:
        build: 
            context: ./wordpress
            dockerfile: Dockerfile
        image: kunwalle/wordpress
        environment:
            - WORDPRESS_DB_PASSWORD: qwerty
        image: "mysql:5.7"
        environment:
            MYSQL_ROOT_PASSWORD: qwerty
        volumes: 
            - ./wordpress
    test-client:
        container_name: test-client
        build:
            context: ./client
            dockerfile: Dockerfile
        command: npm run test
    
    nginx:
        image: nginx:alpine
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./cert/:/etc/nginx/certs


 

